import { readFile } from 'node:fs/promises';
import { Script, createContext } from 'node:vm';
import { parseHTML } from '../.runtime/linkedom.mjs';
const { document, window } = parseHTML(await readFile(new URL('../music.htm', import.meta.url), 'utf8'));
const context = createContext({ document, window, console });
new Script(await readFile(new URL('../music.js', import.meta.url), 'utf8')).runInContext(context);
const run = source => new Script(source).runInContext(context);
let count = 0;
const check = (condition, label) => { if (!condition) throw Error('FAIL: ' + label); count++; console.log('PASS ' + label); };
run(`
    dom = {}; document.querySelectorAll('[id]').forEach(el => dom[el.id] = el);
    cfg = { playlist: [{path:'a.mp3'}, {path:'b.mp3'}, {path:'c.mp3'}], index:1, locked:false };
    getSongInfo = path => ({title:path});
    getAlbumInfo = () => '';
    log = () => {};
    resizePlaylist = () => {};
    undimSong = () => {};
    setTrashPos = () => {};
    cfg.playlist.forEach(song => dom.playlist.appendChild(playlistItem(song)));
`);
run("togglePlayerDrawer('playlistdiv')");
check(!document.getElementById('playlistdiv').hidden && document.getElementById('queue-toggle').getAttribute('aria-expanded') === 'true', 'queue icon opens floating panel');
run("togglePlayerDrawer('player-tools')");
check(document.getElementById('playlistdiv').hidden && !document.getElementById('player-tools').hidden, 'only one floating panel is open');
run('closePlayerDrawers(true)');
check(document.getElementById('playlistdiv').hidden && document.getElementById('player-tools').hidden, 'close panels restores collapsed state');
const event = { preventDefault() {}, stopPropagation() {} };
const queue = document.getElementById('playlist');
queue.children[0].querySelectorAll('button')[1].onclick(event);
check(run("cfg.playlist.map(x=>x.path).join(',')") === 'b.mp3,a.mp3,c.mp3' && run('cfg.index') === 0, 'moving a queue song preserves current playback position');
queue.children[2].querySelectorAll('button')[0].onclick(event);
check(run("cfg.playlist.map(x=>x.path).join(',')") === 'b.mp3,c.mp3,a.mp3', 'queue up button changes order');
queue.children[1].querySelectorAll('button')[2].onclick(event);
check(run("cfg.playlist.map(x=>x.path).join(',')") === 'b.mp3,a.mp3' && queue.children.length === 2, 'remove button deletes only selected queue entry');
run('cfg.locked=true');
queue.children[0].querySelectorAll('button')[2].onclick(event);
check(queue.children.length === 2, 'queue controls respect player lock');
run('cfg.locked=false; drag=dom.playlist.children[0]');
context.dropEvent = { ...event, target: queue.children[1].querySelector('button'), dataTransfer: { getData: () => '0' } };
run('dropItem(dropEvent)');
check(queue.children.length === 2, 'drop on nested queue controls resolves to song row');
const layout = await readFile(new URL('../music.layout.css', import.meta.url), 'utf8');
check(/#player\s*\{[^}]*position:\s*fixed;[^}]*bottom:\s*0/.test(layout), 'player layout is permanently bottom-docked');
check(/#player > \.player-drawer\s*\{[^}]*bottom:\s*calc\(100%/.test(layout), 'queue panel opens above dock');
run("audio = [{duration:240,currentTime:0}]; track=0; dom.seek.value='0.5'; seek('i')");
check(run('audio[0].currentTime') === 0 && run('onSeek') === true, 'dragging previews seek position without restarting audio');
run("seek('c')");
check(run('audio[0].currentTime') === 120 && run('onSeek') === false, 'committing midpoint seeks to half of duration');
run("audio[0].duration=NaN; dom.seek.value='0.75'; seek('c')");
check(run('audio[0].currentTime') === 120, 'unknown duration does not reset playback position');
run("var root='library/';");
check(run("audioSource('Artist & title.mp3')") === 'charts.php?action=audio&source=library%2FArtist%20%26%20title.mp3', 'playback uses byte-range endpoint with encoded path');
run("root='library/Album/';");
check(run("audioSource('song.mp3')") === 'charts.php?action=audio&source=library%2FAlbum%2Fsong.mp3', 'shared folder keeps full track path');
run("root='';");
check(run("audioSource('library/song.mp3')") === 'charts.php?action=audio&source=library%2Fsong.mp3', 'shared single song uses same streaming endpoint');
run(`audio = [{ path:'a.mp3', paused:false, ended:false, currentTime:75,
    pause() { this.paused = true; }, play() { this.paused = false; } }]; track=0;`);
window.playChartSong('a.mp3');
check(run('audio[0].paused && audio[0].currentTime === 75'), 'clicking active library song pauses without seeking');
window.playChartSong('a.mp3');
check(run('!audio[0].paused && audio[0].currentTime === 75'), 'clicking paused library song resumes from same position');
check(window.getMusicPlaybackState().path === 'a.mp3' && window.getMusicPlaybackState().playing, 'playback state uses loaded song independently of queue order');
console.log(`${count} player assertions passed.`);
